#!/bin/bash

# Check if everything has been compiled
make

# Fetch filename from argv
if [ -z ${BASH_ARGV[0]} ]; then 
    filen="resfinal"
else 
    filen=${BASH_ARGV[0]}
fi

echo $filen'.txt'

# Storing runs in text files

./obl2.x 200 0.01 2 $filen'1.txt' $filen'1_vec.txt'
./obl2.x 200 0.01 8 $filen'2.txt' $filen'2_vec.txt'
./obl2.x 200 0.01 16 $filen'3.txt' $filen'3_vec.txt'
./obl2.x 200 0.01 32 $filen'4.txt' $filen'4_vec.txt'
